version: 1
backend:
  phases:
    preBuild:
      commands:
        - echo "Installing dependencies for Lambda functions"
        - cd src/backend/lambda/content && npm install && cd ../../../..
        - cd src/backend/lambda/sites && npm install && cd ../../../..
        - cd src/backend/lambda/topics && npm install && cd ../../../..
        - cd src/backend/lambda/schedules && npm install && cd ../../../..
        - cd src/backend/lambda/settings && npm install && cd ../../../..
        - cd src/backend/lambda/ai-providers && npm install && cd ../../../..
        - cd src/backend/lambda/auth && npm install && cd ../../../..
        - cd src/backend/lambda/crawler && npm install && cd ../../../..
    build:
      commands:
        - echo "Deploying backend changes with Amplify Push"
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci --cache .npm --prefer-offline
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - .npm/**/*
      - node_modules/**/*